name: Scheduled Message

on:
  schedule:
  - cron: "20 * * * *"

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send GET request
        env:
          ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE: ${{ secrets.MESSAGE }}
        run: |
          for i in {1..8}; do curl -H "Authorization: ${ACCOUNT_TOKEN}" -H "Content-Type: application/json" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) discord/1.0.9153 Chrome/124.0.6367.243 Electron/30.1.0 Safari/537.36" -d '{"content": "${{ secrets.MESSAGE }}"}' "https://discord.com/api/v9/channels/${CHANNEL_ID}/messages" > /dev/null 2>&1;done;
